### ISSUE TITLE
Error during setup of component lightwave2

### ISSUE THREAD

**Issue by MiralDesai** [bigbadblunt/home-assistant-custom-components#2]
Getting the following error when trying to use this component with hass.io

```
Error during setup of component lightwave2
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/setup.py", line 145, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/lightwave2.py", line 24, in async_setup
    from lightwave2 import lightwave2
ModuleNotFoundError: No module named 'lightwave2'
```

Not sure if it's hass.io related or not but it doesn't seem to be since it can find the right files. Happy to try and help debug, having this working on hass.io would be pretty good.

**Comment by mpk1001** [comment]
I have this working okay on hass.io.

Do you also have the files from the project: https://github.com/bigbadblunt/lightwave2 in your custom_components?

This homeassistant project provides the integration with HA but it needs the other project to do the communication with lightwave.

**Comment by bigbadblunt** [comment]
Agreed with mpk1001 - this is a missing dependency. Apols, I don;t know how hass.io manages dependencies...

**Comment by bigbadblunt** [comment]
The dependency is also hosted on pypi - you can pip -install lightwave2. The latest version there should work. I'm not sure where you need to install for hass.io though (for vanilla Home Assistant this all happens automatically).

**Comment by MiralDesai** [comment]
Thanks @mpk1001, I don't have those files so will add them. Good to know it works as well.
