### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by BNWEIN** [bigbadblunt/home-assistant-custom-components#4]
Hi.

Firstly thanks for the plugin 

It’s been working perfectly for sometime! I’d be lost without it and actually I am! The last few days (no changes or updated to my home assistant) the entities stop showing up. This shows in the log

homeassistant.setup] Error during setup of component lightwave2
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/setup.py", line 145, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/lightwave2.py", line 32, in async_setup
    await link.async_get_hierarchy()
  File "/config/deps/lib/python3.6/site-packages/lightwave2/lightwave2.py", line 179, in async_get_hierarchy
    await self._async_read_groups(group_ids)
  File "/config/deps/lib/python3.6/site-packages/lightwave2/lightwave2.py", line 221, in _async_read_groups
    y.features[x["attributes"]["type"]] = [x["featureId"], x["attributes"]["value"]]
KeyError: 'value'

Appreciate any help! Desperate to have this working again!

**Comment by trevm8** [comment]
I can second this... exact same error. It was working yesterday and today the platform is failing to load. I have not performed any updates on that period.

**Comment by bigbadblunt** [comment]
Have you tried using the version pushed yesterday? It looks like Lightwave changed something in the messages passed from their server, but I think I've fixed it already!

**Comment by trevm8** [comment]
thank you for responding so fast. I will update the components today and check. Have you considered making the project compatible with HACS? I just installed it last week and so far the automatic updates seem great with other integrations

**Comment by BNWEIN** [comment]
I can confirm the update has fixed the issues 

Thank you soo much for the quick response!

**Comment by bigbadblunt** [comment]
I've also added this to HACS now. If you could try it our and let me know any problems.
